# Install script for directory: /home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv-3.4.5/modules

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv-linux-aarch64-full")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "1")
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "TRUE")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/calib3d/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/core/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/cudaarithm/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/cudabgsegm/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/cudacodec/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/cudafeatures2d/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/cudafilters/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/cudaimgproc/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/cudalegacy/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/cudaobjdetect/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/cudaoptflow/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/cudastereo/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/cudawarping/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/cudev/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/dnn/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/features2d/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/flann/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/highgui/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/imgcodecs/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/imgproc/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/java/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/js/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/ml/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/objdetect/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/photo/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/python/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/shape/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/stitching/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/superres/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/ts/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/video/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/videoio/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/videostab/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/viz/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/.firstpass/world/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/core/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/imgproc/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/java_bindings_generator/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/video/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/imgcodecs/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/shape/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/videoio/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/highgui/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/superres/cmake_install.cmake")
  include("/home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules/python_bindings_generator/cmake_install.cmake")

endif()

