# CMake generated Testfile for 
# Source directory: /home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv-3.4.5/modules
# Build directory: /home/zw/嵌入式设计竞赛资料/项目代码及量化模型/demo/opencv_build_aarch64/modules
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs(".firstpass/calib3d")
subdirs(".firstpass/core")
subdirs(".firstpass/cudaarithm")
subdirs(".firstpass/cudabgsegm")
subdirs(".firstpass/cudacodec")
subdirs(".firstpass/cudafeatures2d")
subdirs(".firstpass/cudafilters")
subdirs(".firstpass/cudaimgproc")
subdirs(".firstpass/cudalegacy")
subdirs(".firstpass/cudaobjdetect")
subdirs(".firstpass/cudaoptflow")
subdirs(".firstpass/cudastereo")
subdirs(".firstpass/cudawarping")
subdirs(".firstpass/cudev")
subdirs(".firstpass/dnn")
subdirs(".firstpass/features2d")
subdirs(".firstpass/flann")
subdirs(".firstpass/highgui")
subdirs(".firstpass/imgcodecs")
subdirs(".firstpass/imgproc")
subdirs(".firstpass/java")
subdirs(".firstpass/js")
subdirs(".firstpass/ml")
subdirs(".firstpass/objdetect")
subdirs(".firstpass/photo")
subdirs(".firstpass/python")
subdirs(".firstpass/shape")
subdirs(".firstpass/stitching")
subdirs(".firstpass/superres")
subdirs(".firstpass/ts")
subdirs(".firstpass/video")
subdirs(".firstpass/videoio")
subdirs(".firstpass/videostab")
subdirs(".firstpass/viz")
subdirs(".firstpass/world")
subdirs("core")
subdirs("imgproc")
subdirs("java_bindings_generator")
subdirs("video")
subdirs("imgcodecs")
subdirs("shape")
subdirs("videoio")
subdirs("highgui")
subdirs("superres")
subdirs("python_bindings_generator")
